# Generated by Django 5.1 on 2024-09-09 09:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0002_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="username",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
